#@TYPE: Machine
#@NAME: i.MX 8M Plus EVK EasyEVSE
#@DESCRIPTION: i.MX 8M Plus Evaluation Kit EasyEVSE configuration
#@MAINTAINER: Octavian-Tiberiu Sirbu <octavian-tiberiu.sirbu@nxp.com>

require conf/machine/imx8mpevk.conf

# Include device trees for other boards for internal test
KERNEL_DEVICETREE += " \
	freescale/imx8mp-evk-evse.dtb \
	freescale/imx8mp-evk-evse-ph1_2-cg5317.dtb \
"

KERNEL_DEVICETREE_BASENAME = "imx8mp-evk"

UBOOT_CONFIG_BASENAME = "imx8mp_evk_evse"
