#@TYPE: Machine
#@NAME: i.MX 8M Mini EVK EasyEVSE
#@DESCRIPTION: i.MX 8M Mini Evaluation Kit EasyEVSE configuration
#@MAINTAINER: Octavian-Tiberiu Sirbu <octavian-tiberiu.sirbu@nxp.com>

require conf/machine/imx8mmevk.conf

# Include device trees for other boards for internal test
KERNEL_DEVICETREE += " \
	freescale/imx8mm-evk-evse.dtb \
	freescale/imx8mm-evk-evse-ph1_2-cg5317.dtb \
"

KERNEL_DEVICETREE_BASENAME = "imx8mm-evk"

UBOOT_CONFIG_BASENAME = "imx8mm_evk_evse"
