#@TYPE: Machine
#@NAME: i.MX 8M Nano EVK EasyEVSE
#@DESCRIPTION: i.MX 8M Nano Evaluation Kit EasyEVSE configuration
#@MAINTAINER: Octavian-Tiberiu Sirbu <octavian-tiberiu.sirbu@nxp.com>

require conf/machine/imx8mnevk.conf

# Include device trees for other boards for internal test
KERNEL_DEVICETREE += " \
	freescale/imx8mn-evk-evse.dtb \
	freescale/imx8mn-evk-evse-ph1_2-cg5317.dtb \
"

KERNEL_DEVICETREE_BASENAME = "imx8mn-evk"

UBOOT_CONFIG_BASENAME = "imx8mn_evk_evse"
