#@TYPE: Machine
#@NAME: i.MX 93 EVK EasyEVSE
#@DESCRIPTION: i.MX 93 Evaluation Kit EasyEVSE configuration
#@MAINTAINER: Octavian-Tiberiu Sirbu <octavian-tiberiu.sirbu@nxp.com>

require conf/machine/imx93evk.conf

# Include device trees for other boards for internal test
KERNEL_DEVICETREE += " \
	freescale/imx93-11x11-evk-evse.dtb \
	freescale/imx93-11x11-evk-evse-lvds.dtb \
	freescale/imx93-11x11-evk-evse-ph1_2-cg5317.dtb \
"

KERNEL_DEVICETREE_BASENAME = "imx93-11x11-evk"
