# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated
inherit qt6-cmake

DESCRIPTION = "EasyEVSE demo with ROS"
AUTHOR = ""
ROS_AUTHOR = ""
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "Apache License 2.0"
LICENSE = "CLOSED"
LIC_FILES_CHKSUM = ""

ROS_BPN = "easyevse"

ROS_BUILD_DEPENDS = " \
    rclcpp \
    rclcpp-components \
	rcl-interfaces \
	rosidl-default-generators \ 
    std-msgs \
    action-msgs \
	packagegroup-qt6-imx \
	qtconnectivity \
	qtsvg \
	qtquick3d-native \
	easyevse-ros-demo-interfaces \
	curl openssl util-linux-libuuid cjson libnfceasyevse sevenstax-v2g libgpiod se05x\
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
    rosidl-default-generators-native \
"

ROS_EXPORT_DEPENDS = ""

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    rosidl-default-runtime \
	rclcpp \
    rclcpp-components \
	rcl-interfaces \
    std-msgs \
	action-msgs \
	easyevse-ros-demo-interfaces weston bash qtsvg-plugins qt5compat cjson libnfceasyevse se05x\
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = " \
    ament-lint-auto \
    ament-lint-common \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

NXP_AZURE_SRC ?= "gitsm://github.com/Azure/azure-iot-sdk-c.git;destsuffix=git/azure-iot-sdk-c;protocol=https"
SRCBRANCH_azure = "lts_01_2023"
SRCREV_azure = "LTS_01_2023_Ref01"

SRCREV_easyevse = "${AUTOREV}"
SRCREV_FORMAT = "easyevse_azure"

# It is required to set the SRCPVs and PV manually because bitbake does not like floating revs like the tag for Azure
SRCPV_azure = "${@bb.fetch2.get_srcrev(d)}"
SRCPV_easyevse = "${@bb.fetch2.get_srcrev(d)}"
PV = "1.0.0+git${SRCPV}"

NXP_EASYEVSE_SRC ?= "git://github.com/nxp-imx-support/nxp-easyevse-mpu.git;protocol=https"
SRCBRANCH_easyevse ?= "${SRC_BRANCH}"

SRC_URI = " ${NXP_EASYEVSE_SRC};branch=${SRCBRANCH_easyevse};name=easyevse \
		 ${NXP_AZURE_SRC};branch=${SRCBRANCH_azure};name=azure \
	"

S = "${WORKDIR}/git/src/easyevse"

ROS_BUILD_TYPE = "ament_cmake"
			
FILES:${PN}= "/usr /usr/cmake"

inherit ros_${ROS_BUILD_TYPE}
