# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "EasyEVSE demo interfaces with ROS"
AUTHOR = ""
ROS_AUTHOR = ""
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "Apache License 2.0"
LICENSE = "CLOSED"
LIC_FILES_CHKSUM = ""

ROS_BPN = "interfaces"

ROS_BUILD_DEPENDS = " \
    rclcpp \
    rclcpp-components \
	rcl-interfaces \
	rosidl-default-generators \ 
    std-msgs \
    action-msgs\
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
    rosidl-default-generators-native \
"

ROS_EXPORT_DEPENDS = ""

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    rosidl-default-runtime \
	rclcpp \
    rclcpp-components \
	rcl-interfaces \
    std-msgs \
	action-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = " \
    ament-lint-auto \
    ament-lint-common \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

NXP_EASYEVSE_SRC ?= "git://github.com/nxp-imx-support/nxp-easyevse-mpu.git;protocol=https"
SRCBRANCH_easyevse ?= "${SRC_BRANCH}"

SRC_URI = " ${NXP_EASYEVSE_SRC};branch=${SRCBRANCH_easyevse}"
SRCREV = "${AUTOREV}"
S = "${WORKDIR}/git/src/interfaces"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
