# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-nxp-evse-common"
BBFILE_PATTERN_meta-nxp-evse-common = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-nxp-evse-common = "8"

LAYERDEPENDS_meta-nxp-evse-common = "fsl-bsp-release imx-demo"
LAYERSERIES_COMPAT_meta-nxp-evse = "langdale mickledore"

SRC_BRANCH ?= "release/easyevse-mpu-3.0"
